---
title: "additional prefixes"
author: "Zachary Houghton"
date: "2025-12-24"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Added a bunch of prefixes --> single model with prefix as RE?

```{r}
library(tidyverse)
library(brms)

corpus = read_csv('../Data/nonce_and_attested_binoms.csv')

data_all_prefixes_all_models_attested_novel = read_csv('../Data/ALL_MODELS_ALL_PREFIXES_NOVEL_AND_ATTESTED.csv') %>%
  mutate(log_odds = preference) %>%
  separate(binom, c('Word1', 'and', 'Word2'), remove = F, sep = ' ') %>%
  select(-and) %>%
  #mutate(across(2:3, tolower)) %>%
  left_join(corpus) %>%
  mutate(checkpoint = 'main') %>%
  mutate(y_vals = 0.02191943 + 0.23925834*Form +  0.24889543*Percept +  0.41836997*Culture +   0.25967334*Power +  0.01867604*Intense +  1.30365980*Icon +   0.08553552*Freq +  0.15241566*Len - 0.19381657*Lapse +  0.36019221*`*BStress`) %>%
  mutate(GenPref = 1/(1+exp(-1*y_vals))) %>%
  mutate(GenPref = GenPref - 0.5)

data_all_prefixes_all_models = read_csv('../Data/ALL_MODELS_ALL_PREFIXES_NOVEL_AND_ATTESTED.csv') %>%
  mutate(log_odds = preference) %>%
  separate(binom, c('Word1', 'and', 'Word2'), remove = F, sep = ' ') %>%
  select(-and) %>%
  #mutate(across(2:3, tolower)) %>%
  left_join(corpus) %>%
  mutate(checkpoint = 'main') %>%
  mutate(y_vals = 0.02191943 + 0.23925834*Form +  0.24889543*Percept +  0.41836997*Culture +   0.25967334*Power +  0.01867604*Intense +  1.30365980*Icon +   0.08553552*Freq +  0.15241566*Len - 0.19381657*Lapse +  0.36019221*`*BStress`) %>%
  mutate(GenPref = 1/(1+exp(-1*y_vals))) %>%
  mutate(GenPref = GenPref - 0.5) %>%
  filter(Attested == 0)





bigram_counts = read_csv('../Data/olmo_bigram_freqs.csv')
onegram_corpus_size = 1560674367427
count_and = 43378012800

bigram_counts = bigram_counts %>%
  mutate(ngram = str_replace_all(ngram, '\t', ' '))


data_all_prefixes_all_models = data_all_prefixes_all_models %>%
  rename(no_final_stress = `*BStress`)



data_all_prefixes_all_models = data_all_prefixes_all_models %>%
  mutate(bigram1_alpha = paste0(Word1, ' and'),
         bigram2_alpha = paste0('and ', Word2),
         bigram1_nonalpha = paste0(Word2, ' and'),
         bigram2_nonalpha = paste0('and ', Word1)
         )

data_all_prefixes_all_models = data_all_prefixes_all_models %>%
  left_join(bigram_counts, by = c('bigram1_alpha' = 'ngram')) %>%
  rename(count_bigram1_alpha = count) %>%
  left_join(bigram_counts, by = c('bigram2_alpha' = 'ngram')) %>%
  rename(count_bigram2_alpha = count) %>%
  left_join(bigram_counts, by = c('bigram1_nonalpha' = 'ngram')) %>%
  rename(count_bigram1_nonalpha = count) %>%
  left_join(bigram_counts, by = c('bigram2_nonalpha' = 'ngram')) %>%
  rename(count_bigram2_nonalpha = count) %>%
  mutate(corpus_size = onegram_corpus_size) %>%
  mutate(count_and = count_and)


data_all_prefixes_all_models = data_all_prefixes_all_models %>%
  mutate(bigram_prob_alpha = (Word1_freq / corpus_size) * (count_bigram1_alpha / Word1_freq) * (count_bigram2_alpha / count_and),
         bigram_prob_nonalpha = (Word2_freq / corpus_size) * (count_bigram1_nonalpha / Word2_freq) * (count_bigram2_nonalpha / count_and),
         log_bigram_prob_alpha = log(bigram_prob_alpha),
         log_bigram_prob_nonalpha = log(bigram_prob_nonalpha),
         log_bigram_odds_ratio = log_bigram_prob_alpha - log_bigram_prob_nonalpha)




```

## Model

```{r}

options(contrasts = c("contr.sum","contr.sum"))

prior_probs = c(
  prior(student_t(3, 0, 5), class = 'Intercept'),
  prior(student_t(3, 0, 5), class = 'sigma'),
  prior(student_t(3, 0, 5), class = 'b')
)

data_all_prefixes_all_models$prompt_value = factor(data_all_prefixes_all_models$prompt_value)

all_models_all_prefixes = brm(log_odds ~ GenPref * model + (GenPref * model | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_all_models,
                       prior = prior_probs,
                       iter = 20000,
                       warmup = 10000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/all_models_all_prefixes'
                      )

# 
# data_all_prefixes_all_models_attested_novel_and_attested = data_all_prefixes_all_models_attested_novel_and_attested %>%
#   mutate(RelFreq = case_when(
#     Attested == 1 ~ RelFreq,
#     Attested == 0 ~ 0),
#     OverallFreq = case_when(
#       Attested == 1 ~ OverallFreq,
#       Attested == 0 ~ 0
#   ))
# data_all_prefixes_all_models_attested_novel$Attested = factor(data_all_prefixes_all_models_attested_novel$Attested)



all_models_all_prefixes_bigrams = brm(log_odds ~ GenPref * model * log_bigram_odds_ratio + (GenPref * model | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_all_models,
                       prior = prior_probs,
                       iter = 20000,
                       warmup = 10000,
                       chains = 4,
                       cores = 4,
                       control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/all_models_all_prefixes_bigrams'
                      )

fixef(all_models_all_prefixes)
fixef(all_models_all_prefixes_bigrams)


data_all_prefixes_gpt2xl = data_all_prefixes_all_models %>%
  filter(model == 'gpt2xl')

data_all_prefixes_olmo2_1b = data_all_prefixes_all_models %>%
  filter(model == 'olmo2_1b')

data_all_prefixes_olmo7b = data_all_prefixes_all_models %>%
  filter(model == 'olmo7b')

data_all_prefixes_gpt2 = data_all_prefixes_all_models %>%
  filter(model == 'gpt2')

data_all_prefixes_gptoss = data_all_prefixes_all_models %>%
  filter(model == 'gptoss120b')

data_all_prefixes_olmo3_32b = data_all_prefixes_all_models %>%
  filter(model == 'olmo3_32b')

data_all_prefixes_olmo3_7b = data_all_prefixes_all_models %>%
  filter(model == 'olmo3_7b')


all_models_gpt2xl = brm(log_odds ~ GenPref + (GenPref | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_gpt2xl,
                       prior = prior_probs,
                       iter = 20000,
                       warmup = 10000,
                       chains = 4,
                       cores = 4,
                       control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/all_models_gpt2xl_all_prefixes'
                      )

all_models_olmo2_1b = brm(log_odds ~ GenPref + (GenPref | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_olmo2_1b,
                       prior = prior_probs,
                       iter = 22000,
                       warmup = 11000,
                       chains = 4,
                       cores = 4,
                       control = list(adapt_delta=0.99, max_treedepth = 17),
                       #control = list(max_treedepth = 20),
                       file = '../Data/all_models_olmo2_1b_all_prefixes'
                      )


prior_probs = c(
  prior(student_t(3, 0, 0.25), class = 'Intercept'),
  prior(student_t(3, 0, 0.25), class = 'sigma'),
  prior(student_t(3, 0, 0.25), class = 'b')
)

all_models_olmo7b = brm(log_odds ~ GenPref + (GenPref | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_olmo7b,
                       prior = prior_probs,
                       iter = 30000,
                       warmup = 15000,
                       chains = 4,
                       cores = 4,
                       control = list(adapt_delta=0.999, max_treedepth = 20),
                       #control = list(max_treedepth = 20),
                       file = '../Data/all_models_olmo7b_all_prefixes'
                      )

all_models_gpt2 = brm(log_odds ~ GenPref + (GenPref | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_gpt2,
                       prior = prior_probs,
                       iter = 30000,
                       warmup = 15000,
                       chains = 4,
                       cores = 4,
                       control = list(adapt_delta=0.999, max_treedepth = 20),
                       #control = list(max_treedepth = 20),
                       file = '../Data/all_models_gpt2'
                      )

all_models_gptoss = brm(log_odds ~ GenPref + (GenPref | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_gptoss,
                       prior = prior_probs,
                       iter = 30000,
                       warmup = 15000,
                       chains = 4,
                       cores = 4,
                       control = list(adapt_delta=0.999, max_treedepth = 20),
                       #control = list(max_treedepth = 20),
                       file = '../Data/all_models_gptoss'
                      )

all_models_olmo3_32b = brm(log_odds ~ GenPref + (GenPref | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_olmo3_32b,
                       prior = prior_probs,
                       iter = 30000,
                       warmup = 15000,
                       chains = 4,
                       cores = 4,
                       control = list(adapt_delta=0.999, max_treedepth = 20),
                       #control = list(max_treedepth = 20),
                       file = '../Data/all_models_olmo3_32b'
                      )

all_models_olmo3_7b = brm(log_odds ~ GenPref + (GenPref | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_olmo3_7b,
                       prior = prior_probs,
                       iter = 30000,
                       warmup = 15000,
                       chains = 4,
                       cores = 4,
                       control = list(adapt_delta=0.999, max_treedepth = 20),
                       #control = list(max_treedepth = 20),
                       file = '../Data/all_models_olmo3_7b'
                      )

fixef(all_models_all_prefixes)
fixef(all_models_gpt2xl)
fixef(all_models_olmo2_1b)
fixef(all_models_olmo7b)
fixef(all_models_gpt2)
fixef(all_models_gptoss)
fixef(all_models_olmo3_32b)
fixef(all_models_olmo3_7b)

```

### random effects plots
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)

# 1. reshape wide (all terms and all metrics)
re_df = ranef(all_models_all_prefixes)$prompt_value

re_df <- as.data.frame.table(re_df, responseName = "value")
names(re_df) <- c("prompt_value", "metric", "term", "value")


re_wide <- re_df %>%
  pivot_wider(
    names_from = c(term, metric),
    values_from = value
  ) %>%
  mutate(
    model3_Estimate = -(model1_Estimate + model2_Estimate),
    model3_Q2.5     = -(model1_Q97.5   + model2_Q97.5),
    model3_Q97.5    = -(model1_Q2.5    + model2_Q2.5)
  )

# 2. pivot long again so ggplot can facet
re_long <- re_wide %>%
  pivot_longer(
    cols = -prompt_value,
    names_to = c("term","metric"),
    names_sep = "_",
    values_to = "value"
  )

# 3. only keep useful terms
plot_df <- re_long %>%
  filter(term %in% c("Intercept","GenPref","model1","model2","model3"))

# 4. create wide data for ribbons
plot_df_wide <- plot_df %>%
  pivot_wider(names_from = metric, values_from = value)

# 5. plot EVERYTHING properly
ggplot(plot_df_wide, aes(x = Estimate, y = prompt_value)) +
  geom_point() +
  geom_errorbarh(aes(xmin = Q2.5, xmax = Q97.5), height = 0) +
  facet_wrap(~ term, scales = "fixed") +
  theme_bw()


```

```{r}
# 1. reshape wide (all terms and all metrics)
re_df = ranef(all_models_all_prefixes_bigrams)$prompt_value

re_df <- as.data.frame.table(re_df, responseName = "value")
names(re_df) <- c("prompt_value", "metric", "term", "value")


re_wide <- re_df %>%
  pivot_wider(
    names_from = c(term, metric),
    values_from = value
  ) %>%
  mutate(
    model3_Estimate = -(model1_Estimate + model2_Estimate),
    model3_Q2.5     = -(model1_Q97.5   + model2_Q97.5),
    model3_Q97.5    = -(model1_Q2.5    + model2_Q2.5)
  )

# 2. pivot long again so ggplot can facet
re_long <- re_wide %>%
  pivot_longer(
    cols = -prompt_value,
    names_to = c("term","metric"),
    names_sep = "_",
    values_to = "value"
  )

# 3. only keep useful terms
plot_df <- re_long %>%
  filter(term %in% c("Intercept","GenPref","model1","model2","model3"))

# 4. create wide data for ribbons
plot_df_wide <- plot_df %>%
  pivot_wider(names_from = metric, values_from = value)

# 5. plot EVERYTHING properly
ggplot(plot_df_wide, aes(x = Estimate, y = prompt_value)) +
  geom_point() +
  geom_errorbarh(aes(xmin = Q2.5, xmax = Q97.5), height = 0) +
  facet_wrap(~ term, scales = "fixed") +
  theme_bw()


```

### individual constraints


```{r}
  


all_models_all_prefixes_all_constraints = brm(log_odds ~ (Culture + Power + Freq + Len + no_final_stress + Intense + Percept + Lapse ) * model + (Culture + Power + Freq + Len + no_final_stress + Intense + Percept + Lapse | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_all_models,
                       prior = prior_probs,
                       iter = 6000,
                       warmup = 3000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/all_models_all_prefixes_all_constraints'
                      )

library(car)

lm_vif <- lm(
  log_odds ~
    (Culture + Power + Freq + Len + no_final_stress +
     Intense + Percept + Lapse),
  data = data_all_prefixes_all_models
)

car::vif(lm_vif)
#drop lapse and no_final_stress
all_models_all_prefixes_all_constraints_vif_dropped = brm(log_odds ~ (Culture + Power + Freq + Len + Intense + Percept) * model + (Culture + Power + Freq + Len + Intense + Percept | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_all_models,
                       prior = prior_probs,
                       iter = 6000,
                       warmup = 3000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/all_models_all_prefixes_all_constraints_vif_dropped'
                      )



fixef(all_models_all_prefixes_all_constraints)
## And now we do backward model selection

```


```{r}

all_models_all_prefixes_individual_constraints = brm(log_odds ~ (Culture + Power + Freq + Len) * model + (Culture + Power + Freq + Len | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_all_models,
                       prior = prior_probs,
                       iter = 6000,
                       warmup = 3000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/all_models_all_prefixes_individual_constraints'
                      )

gpt2xl_all_prefixes_individual_constraints = brm(log_odds ~ (Culture + Power + Freq + Len) + (Culture + Power + Freq + Len | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_gpt2xl,
                       prior = prior_probs,
                       iter = 6000,
                       warmup = 3000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/gpt2xl_all_prefixes_individual_constraints'
                      )

olmo2_1b_all_prefixes_individual_constraints = brm(log_odds ~ (Culture + Power + Freq + Len) + (Culture + Power + Freq + Len | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_olmo2_1b,
                       prior = prior_probs,
                       iter = 9000,
                       warmup = 4500,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/olmo2_1b_all_prefixes_individual_constraints'
                      )

olmo7b_all_prefixes_individual_constraints = brm(log_odds ~ (Culture + Power + Freq + Len) + (Culture + Power + Freq + Len | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_olmo7b,
                       prior = prior_probs,
                       iter = 8000,
                       warmup = 4000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/olmo7b_all_prefixes_individual_constraints'
                      )

# olmo7b_all_prefixes_individual_constraints_test = brm(log_odds ~ (Culture + Power + Freq + Len) + (1 | prompt_value) + ( 1 | Alpha),
#                        data = data_all_prefixes_olmo7b,
#                        prior = prior_probs,
#                        iter = 8000,
#                        warmup = 4000,
#                        chains = 4,
#                        cores = 4,
#                        #control = list(adapt_delta=0.99, max_treedepth = 15),
#                        #control = list(max_treedepth = 20),
#                        #file = '../Data/olmo7b_all_prefixes_individual_constraints'
#                       )

gpt2_all_prefixes_individual_constraints = brm(log_odds ~ (Culture + Power + Freq + Len) + (Culture + Power + Freq + Len | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_gpt2,
                       prior = prior_probs,
                       iter = 8000,
                       warmup = 4000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/gpt2_all_prefixes_individual_constraints_test'
                      )


gptoss_all_prefixes_individual_constraints = brm(log_odds ~ (Culture + Power + Freq + Len) + (Culture + Power + Freq + Len | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_gptoss,
                       prior = prior_probs,
                       iter = 8000,
                       warmup = 4000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/gptoss_all_prefixes_individual_constraints'
                      )

olmo3_32b_all_prefixes_individual_constraints = brm(log_odds ~ (Culture + Power + Freq + Len) + (Culture + Power + Freq + Len | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_olmo3_32b,
                       prior = prior_probs,
                       iter = 8000,
                       warmup = 4000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/olmo3_32b_all_prefixes_individual_constraints'
                      )

olmo3_7b_all_prefixes_individual_constraints = brm(log_odds ~ (Culture + Power + Freq + Len) + (Culture + Power + Freq + Len | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_olmo3_7b,
                       prior = prior_probs,
                       iter = 8000,
                       warmup = 4000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/olmo3_7b_all_prefixes_individual_constraints'
                      )

fixef(all_models_all_prefixes_individual_constraints)
fixef(gpt2xl_all_prefixes_individual_constraints)
fixef(olmo2_1b_all_prefixes_individual_constraints)
fixef(olmo7b_all_prefixes_individual_constraints)
fixef(gpt2_all_prefixes_individual_constraints)
fixef(gptoss_all_prefixes_individual_constraints)
fixef(olmo3_32b_all_prefixes_individual_constraints)
fixef(olmo3_7b_all_prefixes_individual_constraints)



```

## Model Selection

```{r}

##Lapse and no_final_stress droppped for having low vif for all models

gpt2xl_all_prefixes_all_constraints = brm(log_odds ~ (Culture + Power + Freq + Len + Intense + Percept) + (Culture + Power + Freq + Len + Intense + Percept | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_gpt2xl,
                       prior = prior_probs,
                       iter = 6000,
                       warmup = 3000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/gpt2xl_all_prefixes_all_constraints'
                      )

gpt2xl_all_prefixes_percept_power_dropped = brm(log_odds ~ (Culture + Freq + Len + Intense) + (Culture + Freq + Len + Intense | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_gpt2xl,
                       prior = prior_probs,
                       iter = 6000,
                       warmup = 3000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/gpt2xl_all_prefixes_percept_power_dropped'
                      )


olmo2_1b_all_prefixes_all_constraints = brm(log_odds ~ (Culture + Power + Freq + Len + Intense + Percept) + (Culture + Power + Freq + Len + Intense + Percept | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_olmo2_1b,
                       prior = prior_probs,
                       iter = 9000,
                       warmup = 4500,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/olmo2_1b_all_prefixes_all_constraints'
                      )

olmo2_1b_all_prefixes_freq_dropped = brm(log_odds ~ (Culture + Power + Len + Intense + Percept) + (Culture + Power + Len + Intense + Percept | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_olmo2_1b,
                       prior = prior_probs,
                       iter = 9000,
                       warmup = 4500,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/olmo2_1b_all_prefixes_freq_dropped'
                      )

olmo7b_all_prefixes_all_constraints = brm(log_odds ~ (Culture + Power + Freq + Len + Intense + Percept) + (Culture + Power + Freq + Len + Intense + Percept | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_olmo7b,
                       prior = prior_probs,
                       iter = 8000,
                       warmup = 4000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/olmo7b_all_prefixes_all_constraints'
                      )

olmo7b_all_prefixes_len_dropped = brm(log_odds ~ (Culture + Power + Freq + Intense + Percept) + (Culture + Power + Freq + Intense + Percept | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_olmo7b,
                       prior = prior_probs,
                       iter = 8000,
                       warmup = 4000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/olmo7b_all_prefixes_len_dropped'
                      )



gpt2_all_prefixes_all_constraints = brm(log_odds ~ (Culture + Power + Freq + Len + Intense + Percept) + (Culture + Power + Freq + Len + Intense + Percept | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_gpt2,
                       prior = prior_probs,
                       iter = 8000,
                       warmup = 4000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/gpt2_all_prefixes_all_constraints'
                      )


gpt2_all_prefixes_freq_intense_dropped = brm(log_odds ~ (Culture + Power + Len + Percept) + (Culture + Power + Len + Percept | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_gpt2,
                       prior = prior_probs,
                       iter = 8000,
                       warmup = 4000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/gpt2_all_prefixes_freq_intense_dropped'
                      )



gptoss_all_prefixes_all_constraints = brm(log_odds ~ (Culture + Power + Freq + Len + Intense + Percept) + (Culture + Power + Freq + Len + Intense + Percept | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_gptoss,
                       prior = prior_probs,
                       iter = 8000,
                       warmup = 4000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/gptoss_all_prefixes_all_constraints'
                      )


gptoss_all_prefixes_culture_percept_dropped = brm(log_odds ~ (Power + Freq + Len + Intense) + (Power + Freq + Len + Intense | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_gptoss,
                       prior = prior_probs,
                       iter = 8000,
                       warmup = 4000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/gptoss_all_prefixes_culture_percept_dropped'
                      )

olmo3_32b_all_prefixes_all_constraints = brm(log_odds ~ (Culture + Power + Freq + Len + Intense + Percept) + (Culture + Power + Freq + Len + Intense + Percept | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_olmo3_32b,
                       prior = prior_probs,
                       iter = 8000,
                       warmup = 4000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/olmo3_32b_all_prefixes_all_constraints'
                      )

olmo3_32b_all_prefixes_freq_dropped = brm(log_odds ~ (Culture + Power + Len + Intense + Percept) + (Culture + Power + Len + Intense + Percept | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_olmo3_32b,
                       prior = prior_probs,
                       iter = 8000,
                       warmup = 4000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/olmo3_32b_all_prefixes_freq_dropped'
                      )

olmo3_7b_all_prefixes_all_constraints = brm(log_odds ~ (Culture + Power + Freq + Len + Intense + Percept) + (Culture + Power + Freq + Len + Intense + Percept | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_olmo3_7b,
                       prior = prior_probs,
                       iter = 8000,
                       warmup = 4000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/olmo3_7b_all_prefixes_all_constraints'
                      )

olmo3_7b_all_prefixes_freq_percept_dropped = brm(log_odds ~ (Culture + Power + Len + Intense) + (Culture + Power + Len + Intense | prompt_value) + ( 1 | Alpha),
                       data = data_all_prefixes_olmo3_7b,
                       prior = prior_probs,
                       iter = 8000,
                       warmup = 4000,
                       chains = 4,
                       cores = 4,
                       #control = list(adapt_delta=0.99, max_treedepth = 15),
                       #control = list(max_treedepth = 20),
                       file = '../Data/olmo3_7b_all_prefixes_freq_percept_dropped'
                      )

fixef(gpt2xl_all_prefixes_all_constraints)
fixef(olmo2_1b_all_prefixes_all_constraints)
fixef(olmo7b_all_prefixes_all_constraints)
fixef(gpt2_all_prefixes_all_constraints)
fixef(gptoss_all_prefixes_all_constraints)
fixef(olmo3_32b_all_prefixes_all_constraints)
fixef(olmo3_7b_all_prefixes_all_constraints)



fixef(gpt2xl_all_prefixes_percept_power_dropped)
fixef(olmo2_1b_all_prefixes_freq_dropped)
fixef(olmo7b_all_prefixes_len_dropped)
fixef(gpt2_all_prefixes_freq_intense_dropped)
fixef(gptoss_all_prefixes_culture_percept_dropped)
fixef(olmo3_32b_all_prefixes_freq_dropped)
fixef(olmo3_7b_all_prefixes_freq_percept_dropped)

```

```{r}
# 1. reshape wide (all terms and all metrics)
re_df = ranef(all_models_all_prefixes_individual_constraints)$prompt_value

re_df <- as.data.frame.table(re_df, responseName = "value")
names(re_df) <- c("prompt_value", "metric", "term", "value")


re_wide <- re_df %>%
  pivot_wider(
    names_from = c(term, metric),
    values_from = value)
  # ) %>%
  # mutate(
  #   model3_Estimate = -(model1_Estimate + model2_Estimate),
  #   model3_Q2.5     = -(model1_Q97.5   + model2_Q97.5),
  #   model3_Q97.5    = -(model1_Q2.5    + model2_Q2.5)
  # )

# 2. pivot long again so ggplot can facet
re_long <- re_wide %>%
  pivot_longer(
    cols = -prompt_value,
    names_to = c("term","metric"),
    names_sep = "_",
    values_to = "value"
  )

# 3. only keep useful terms
plot_df <- re_long %>%
  filter(term %in% c("Intercept","Power","Freq","Len"))

# 4. create wide data for ribbons
plot_df_wide <- plot_df %>%
  pivot_wider(names_from = metric, values_from = value)

# 5. plot EVERYTHING properly
ggplot(plot_df_wide, aes(x = Estimate, y = prompt_value)) +
  geom_point() +
  geom_errorbarh(aes(xmin = Q2.5, xmax = Q97.5), height = 0) +
  facet_wrap(~ term, scales = "fixed") +
  theme_bw()

```